### ISSUE TITLE
Can't run the commend with error "undefined: Blog"

### ISSUE THREAD

**Issue by Kara-ism** [muflax/tumblr-backup#1]
Hi, 

As I mentioned in tittle,
I can't run run the commend (tumblr-backup.go) with error "undefined: Blog" in line 83.

Could you fix that problem? Thank you!
<img width="426" alt="0" src="https://cloud.githubusercontent.com/assets/9511279/11979283/0d9a3dda-a9cd-11e5-97a9-e5c2b9d42323.PNG">

**Comment by muflax** [comment]
Yeah, the tool is still unfinished and not usable yet. Try using [tumblr-utils](https://github.com/bbolli/tumblr-utils).
